import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    name: 'English',
    flag: '🇬🇧',
    nav: {
      home: 'Home',
      pharmacyServices: 'Pharmacy Services',
      pharmacyStore: 'Pharmacy Store',
      reviews: 'Reviews',
      login: 'Login',
      signup: 'Sign Up',
      dashboard: 'Dashboard',
      logout: 'Logout',
      notifications: 'Notifications',
    },
    pharmacy: {
      searchPlaceholder: 'Search medicines, brands, symptoms…',
      addToCart: 'Add to Cart',
      outOfStock: 'Out of Stock',
      viewCart: 'View Cart',
      allMedicines: 'All Medicines',
      favorites: 'Favorites',
      uploadPrescription: 'Upload Prescription',
      filterBy: 'Filter By',
      brand: 'Brand',
      manufacturer: 'Manufacturer',
      composition: 'Composition',
      priceRange: 'Price Range',
      applyFilters: 'Apply Filters',
      clearFilters: 'Clear Filters',
    },
    chatbot: {
      title: 'MedBot Assistant',
      placeholder: 'Ask about medicines, orders…',
      send: 'Send',
      greeting: 'Hello! I\'m MedBot. How can I help you today?',
    },
    offline: {
      banner: 'You are offline. Some features may be unavailable.',
    },
    notifications: {
      title: 'Notifications Hub',
      push: 'Push Notifications',
      email: 'Email Notifications',
      sms: 'SMS Notifications',
      orderUpdates: 'Order Updates',
      prescriptionReminders: 'Prescription Reminders',
      offerAlerts: 'Offer & Discount Alerts',
      healthReminders: 'Health Reminders',
      save: 'Save Preferences',
      saved: 'Preferences saved!',
    },
  },
  hi: {
    name: 'हिंदी',
    flag: '🇮🇳',
    nav: {
      home: 'होम',
      pharmacyServices: 'फार्मेसी सेवाएं',
      pharmacyStore: 'फार्मेसी स्टोर',
      reviews: 'समीक्षाएं',
      login: 'लॉगिन',
      signup: 'साइन अप',
      dashboard: 'डैशबोर्ड',
      logout: 'लॉगआउट',
      notifications: 'सूचनाएं',
    },
    pharmacy: {
      searchPlaceholder: 'दवाइयां, ब्रांड, लक्षण खोजें…',
      addToCart: 'कार्ट में जोड़ें',
      outOfStock: 'स्टॉक में नहीं',
      viewCart: 'कार्ट देखें',
      allMedicines: 'सभी दवाइयां',
      favorites: 'पसंदीदा',
      uploadPrescription: 'प्रिस्क्रिप्शन अपलोड करें',
      filterBy: 'फ़िल्टर करें',
      brand: 'ब्रांड',
      manufacturer: 'निर्माता',
      composition: 'संरचना',
      priceRange: 'मूल्य सीमा',
      applyFilters: 'फ़िल्टर लागू करें',
      clearFilters: 'फ़िल्टर हटाएं',
    },
    chatbot: {
      title: 'मेडबॉट सहायक',
      placeholder: 'दवाइयों, ऑर्डर के बारे में पूछें…',
      send: 'भेजें',
      greeting: 'नमस्ते! मैं मेडबॉट हूं। आज मैं आपकी कैसे मदद कर सकता हूं?',
    },
    offline: {
      banner: 'आप ऑफलाइन हैं। कुछ सुविधाएं उपलब्ध नहीं हो सकती हैं।',
    },
    notifications: {
      title: 'सूचना केंद्र',
      push: 'पुश सूचनाएं',
      email: 'ईमेल सूचनाएं',
      sms: 'SMS सूचनाएं',
      orderUpdates: 'ऑर्डर अपडेट',
      prescriptionReminders: 'प्रिस्क्रिप्शन रिमाइंडर',
      offerAlerts: 'ऑफर और छूट अलर्ट',
      healthReminders: 'स्वास्थ्य रिमाइंडर',
      save: 'प्राथमिकताएं सहेजें',
      saved: 'प्राथमिकताएं सहेजी गईं!',
    },
  },
  ta: {
    name: 'தமிழ்',
    flag: '🇮🇳',
    nav: {
      home: 'முகப்பு',
      pharmacyServices: 'மருந்தக சேவைகள்',
      pharmacyStore: 'மருந்தகம்',
      reviews: 'மதிப்புரைகள்',
      login: 'உள்நுழைய',
      signup: 'பதிவு செய்',
      dashboard: 'டாஷ்போர்டு',
      logout: 'வெளியேறு',
      notifications: 'அறிவிப்புகள்',
    },
    pharmacy: {
      searchPlaceholder: 'மருந்துகள், பிராண்டுகள் தேடுங்கள்…',
      addToCart: 'கார்ட்டில் சேர்',
      outOfStock: 'கையிருப்பில் இல்லை',
      viewCart: 'கார்ட் பார்க்க',
      allMedicines: 'அனைத்து மருந்துகள்',
      favorites: 'விருப்பமானவை',
      uploadPrescription: 'மருந்துச்சீட்டு பதிவேற்றம்',
      filterBy: 'வடிகட்டு',
      brand: 'பிராண்டு',
      manufacturer: 'உற்பத்தியாளர்',
      composition: 'கலவை',
      priceRange: 'விலை வரம்பு',
      applyFilters: 'வடிகட்டிகள் பயன்படுத்து',
      clearFilters: 'வடிகட்டிகள் அழி',
    },
    chatbot: {
      title: 'மெட்பாட் உதவியாளர்',
      placeholder: 'மருந்துகள், ஆர்டர்கள் பற்றி கேளுங்கள்…',
      send: 'அனுப்பு',
      greeting: 'வணக்கம்! நான் மெட்பாட். இன்று நான் உங்களுக்கு எப்படி உதவலாம்?',
    },
    offline: {
      banner: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். சில அம்சங்கள் கிடைக்காமல் போகலாம்.',
    },
    notifications: {
      title: 'அறிவிப்பு மையம்',
      push: 'புஷ் அறிவிப்புகள்',
      email: 'மின்னஞ்சல் அறிவிப்புகள்',
      sms: 'SMS அறிவிப்புகள்',
      orderUpdates: 'ஆர்டர் புதுப்பிப்புகள்',
      prescriptionReminders: 'மருந்துச்சீட்டு நினைவூட்டல்கள்',
      offerAlerts: 'சலுகை & தள்ளுபடி விழிப்பூட்டல்கள்',
      healthReminders: 'உடல்நல நினைவூட்டல்கள்',
      save: 'விருப்பங்களை சேமி',
      saved: 'விருப்பங்கள் சேமிக்கப்பட்டன!',
    },
  },
  te: {
    name: 'తెలుగు',
    flag: '🇮🇳',
    nav: {
      home: 'హోమ్',
      pharmacyServices: 'ఫార్మసీ సేవలు',
      pharmacyStore: 'ఫార్మసీ స్టోర్',
      reviews: 'సమీక్షలు',
      login: 'లాగిన్',
      signup: 'సైన్ అప్',
      dashboard: 'డాష్‌బోర్డ్',
      logout: 'లాగౌట్',
      notifications: 'నోటిఫికేషన్లు',
    },
    pharmacy: {
      searchPlaceholder: 'మందులు, బ్రాండ్లు శోధించండి…',
      addToCart: 'కార్ట్‌కు జోడించు',
      outOfStock: 'స్టాక్‌లో లేదు',
      viewCart: 'కార్ట్ చూడు',
      allMedicines: 'అన్ని మందులు',
      favorites: 'ఇష్టమైనవి',
      uploadPrescription: 'ప్రిస్క్రిప్షన్ అప్‌లోడ్',
      filterBy: 'వడపోత',
      brand: 'బ్రాండ్',
      manufacturer: 'తయారీదారు',
      composition: 'కూర్పు',
      priceRange: 'ధర పరిధి',
      applyFilters: 'ఫిల్టర్లు వర్తించు',
      clearFilters: 'ఫిల్టర్లు తొలగించు',
    },
    chatbot: {
      title: 'మెడ్‌బాట్ అసిస్టెంట్',
      placeholder: 'మందులు, ఆర్డర్ల గురించి అడగండి…',
      send: 'పంపు',
      greeting: 'నమస్కారం! నేను మెడ్‌బాట్. నేను మీకు ఎలా సహాయం చేయగలను?',
    },
    offline: {
      banner: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. కొన్ని ఫీచర్లు అందుబాటులో ఉండకపోవచ్చు.',
    },
    notifications: {
      title: 'నోటిఫికేషన్ హబ్',
      push: 'పుష్ నోటిఫికేషన్లు',
      email: 'ఇమెయిల్ నోటిఫికేషన్లు',
      sms: 'SMS నోటిఫికేషన్లు',
      orderUpdates: 'ఆర్డర్ అప్‌డేట్లు',
      prescriptionReminders: 'ప్రిస్క్రిప్షన్ రిమైండర్లు',
      offerAlerts: 'ఆఫర్ & డిస్కౌంట్ హెచ్చరికలు',
      healthReminders: 'ఆరోగ్య రిమైండర్లు',
      save: 'ప్రాధాన్యతలు సేవ్ చేయి',
      saved: 'ప్రాధాన్యతలు సేవ్ అయ్యాయి!',
    },
  },
  kn: {
    name: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    nav: {
      home: 'ಮುಖಪುಟ',
      pharmacyServices: 'ಔಷಧಾಲಯ ಸೇವೆಗಳು',
      pharmacyStore: 'ಔಷಧಾಲಯ ಅಂಗಡಿ',
      reviews: 'ವಿಮರ್ಶೆಗಳು',
      login: 'ಲಾಗಿನ್',
      signup: 'ಸೈನ್ ಅಪ್',
      dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      logout: 'ಲಾಗ್‌ಔಟ್',
      notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    },
    pharmacy: {
      searchPlaceholder: 'ಔಷಧಗಳು, ಬ್ರಾಂಡ್‌ಗಳನ್ನು ಹುಡುಕಿ…',
      addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
      outOfStock: 'ಸ್ಟಾಕ್ ಇಲ್ಲ',
      viewCart: 'ಕಾರ್ಟ್ ನೋಡಿ',
      allMedicines: 'ಎಲ್ಲಾ ಔಷಧಗಳು',
      favorites: 'ನೆಚ್ಚಿನವುಗಳು',
      uploadPrescription: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್',
      filterBy: 'ಫಿಲ್ಟರ್ ಮಾಡಿ',
      brand: 'ಬ್ರಾಂಡ್',
      manufacturer: 'ತಯಾರಕ',
      composition: 'ಸಂಯೋಜನೆ',
      priceRange: 'ಬೆಲೆ ವ್ಯಾಪ್ತಿ',
      applyFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ',
      clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    },
    chatbot: {
      title: 'ಮೆಡ್‌ಬಾಟ್ ಸಹಾಯಕ',
      placeholder: 'ಔಷಧಗಳು, ಆರ್ಡರ್‌ಗಳ ಬಗ್ಗೆ ಕೇಳಿ…',
      send: 'ಕಳುಹಿಸಿ',
      greeting: 'ನಮಸ್ಕಾರ! ನಾನು ಮೆಡ್‌ಬಾಟ್. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    },
    offline: {
      banner: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ. ಕೆಲವು ವೈಶಿಷ್ಟ್ಯಗಳು ಲಭ್ಯವಿಲ್ಲದಿರಬಹುದು.',
    },
    notifications: {
      title: 'ಅಧಿಸೂಚನೆ ಹಬ್',
      push: 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
      email: 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
      sms: 'SMS ಅಧಿಸೂಚನೆಗಳು',
      orderUpdates: 'ಆರ್ಡರ್ ಅಪ್‌ಡೇಟ್‌ಗಳು',
      prescriptionReminders: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ರಿಮೈಂಡರ್‌ಗಳು',
      offerAlerts: 'ಆಫರ್ & ರಿಯಾಯಿತಿ ಎಚ್ಚರಿಕೆಗಳು',
      healthReminders: 'ಆರೋಗ್ಯ ರಿಮೈಂಡರ್‌ಗಳು',
      save: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
      saved: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ!',
    },
  },
  bn: {
    name: 'বাংলা',
    flag: '🇮🇳',
    nav: {
      home: 'হোম',
      pharmacyServices: 'ফার্মেসি সেবা',
      pharmacyStore: 'ফার্মেসি স্টোর',
      reviews: 'পর্যালোচনা',
      login: 'লগইন',
      signup: 'সাইন আপ',
      dashboard: 'ড্যাশবোর্ড',
      logout: 'লগআউট',
      notifications: 'বিজ্ঞপ্তি',
    },
    pharmacy: {
      searchPlaceholder: 'ওষুধ, ব্র্যান্ড অনুসন্ধান করুন…',
      addToCart: 'কার্টে যোগ করুন',
      outOfStock: 'স্টকে নেই',
      viewCart: 'কার্ট দেখুন',
      allMedicines: 'সমস্ত ওষুধ',
      favorites: 'প্রিয়',
      uploadPrescription: 'প্রেসক্রিপশন আপলোড করুন',
      filterBy: 'ফিল্টার করুন',
      brand: 'ব্র্যান্ড',
      manufacturer: 'প্রস্তুতকারক',
      composition: 'গঠন',
      priceRange: 'মূল্য পরিসর',
      applyFilters: 'ফিল্টার প্রয়োগ করুন',
      clearFilters: 'ফিল্টার সাফ করুন',
    },
    chatbot: {
      title: 'মেডবট সহকারী',
      placeholder: 'ওষুধ, অর্ডার সম্পর্কে জিজ্ঞাসা করুন…',
      send: 'পাঠান',
      greeting: 'নমস্কার! আমি মেডবট। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
    },
    offline: {
      banner: 'আপনি অফলাইনে আছেন। কিছু বৈশিষ্ট্য অনুপলব্ধ হতে পারে।',
    },
    notifications: {
      title: 'বিজ্ঞপ্তি হাব',
      push: 'পুশ বিজ্ঞপ্তি',
      email: 'ইমেল বিজ্ঞপ্তি',
      sms: 'SMS বিজ্ঞপ্তি',
      orderUpdates: 'অর্ডার আপডেট',
      prescriptionReminders: 'প্রেসক্রিপশন রিমাইন্ডার',
      offerAlerts: 'অফার ও ছাড় সতর্কতা',
      healthReminders: 'স্বাস্থ্য রিমাইন্ডার',
      save: 'পছন্দ সংরক্ষণ করুন',
      saved: 'পছন্দ সংরক্ষিত হয়েছে!',
    },
  },
  mr: {
    name: 'मराठी',
    flag: '🇮🇳',
    nav: {
      home: 'मुखपृष्ठ',
      pharmacyServices: 'फार्मसी सेवा',
      pharmacyStore: 'फार्मसी दुकान',
      reviews: 'पुनरावलोकने',
      login: 'लॉगिन',
      signup: 'साइन अप',
      dashboard: 'डॅशबोर्ड',
      logout: 'लॉगआउट',
      notifications: 'सूचना',
    },
    pharmacy: {
      searchPlaceholder: 'औषधे, ब्रँड्स शोधा…',
      addToCart: 'कार्टमध्ये जोडा',
      outOfStock: 'स्टॉकमध्ये नाही',
      viewCart: 'कार्ट पहा',
      allMedicines: 'सर्व औषधे',
      favorites: 'आवडते',
      uploadPrescription: 'प्रिस्क्रिप्शन अपलोड करा',
      filterBy: 'फिल्टर करा',
      brand: 'ब्रँड',
      manufacturer: 'निर्माता',
      composition: 'रचना',
      priceRange: 'किंमत श्रेणी',
      applyFilters: 'फिल्टर लागू करा',
      clearFilters: 'फिल्टर साफ करा',
    },
    chatbot: {
      title: 'मेडबॉट सहाय्यक',
      placeholder: 'औषधे, ऑर्डरबद्दल विचारा…',
      send: 'पाठवा',
      greeting: 'नमस्कार! मी मेडबॉट आहे. आज मी तुम्हाला कशी मदत करू शकतो?',
    },
    offline: {
      banner: 'तुम्ही ऑफलाइन आहात. काही वैशिष्ट्ये उपलब्ध नसू शकतात.',
    },
    notifications: {
      title: 'सूचना हब',
      push: 'पुश सूचना',
      email: 'ईमेल सूचना',
      sms: 'SMS सूचना',
      orderUpdates: 'ऑर्डर अपडेट्स',
      prescriptionReminders: 'प्रिस्क्रिप्शन स्मरणपत्रे',
      offerAlerts: 'ऑफर आणि सवलत सूचना',
      healthReminders: 'आरोग्य स्मरणपत्रे',
      save: 'प्राधान्ये जतन करा',
      saved: 'प्राधान्ये जतन केली!',
    },
  },
};

const SUPPORTED_LANGUAGES = Object.entries(translations).map(([code, t]) => ({
  code,
  name: t.name,
  flag: t.flag,
}));

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('medVisionLanguage') || 'en';
  });

  const t = translations[language] || translations.en;

  const changeLanguage = (code) => {
    if (translations[code]) {
      setLanguage(code);
      localStorage.setItem('medVisionLanguage', code);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage, SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
